# Site settings
title: Trung Nguyen
header-img: img/home-bg.jpg
gemail: geek1706@gmail.com
copyright_name: geek
description: "Dev Notes and Thoughts"
baseurl: ""
url: "geek1706.github.io"
twitter_username: geek1706
github_username:  geek1706
facebook_username:  
email_username:  geek1706@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]
